article/urls.py
from django.contrib import admin
from django.urls import path
from article import views

app_name= "article"

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('createarticle/', views.createArticle, name="createarticle"),
    path('article/<int:id>',views.showDetail,name="showdetail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('', views.articles, name="article"),
    path('comment/<int:id>',views.addComment,name="comment"),
]

blogApp/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name= "index"),
    path("index/",views.index,name= "index"),
    path("about/",views.about,name="about"),
    path("articles/",include("article.urls")),
    path("user/",include("user.urls"))

]
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name= "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

article/models.py
from django.db import models

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_image = models.FileField(blank=True, null= True, verbose_name="Add file to article")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Article",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="name")
    comment_content = models.CharField(max_length=250,verbose_name="comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username= forms.CharField(label="User name")
    password= forms.CharField(label= "Password",widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label="User Name")
    password = forms.CharField(max_length=20,label="Password",widget=forms.PasswordInput)
    confirm =  forms.CharField(max_length=20,label="Confirmation",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords are not the same")
        values ={
            "username": username,
            "password": password
        }
        return values

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from django.contrib import messages
from article.forms import ArticleForm
from django.contrib.auth.decorators import login_required

from article.models import Article,Comment


# Create your views here.
def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})
def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        "articles": articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url="user:login")
def createArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article=form.save(commit=False)
        article.author= request.user
        article.save()
        messages.success(request,"Article succesfully created")
        return redirect("index")
    return render(request,"createarticle.html",{"form":form})


def showDetail(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Article succesfully updated")
        return redirect("article:dashboard")

    return render(request,"update.html",{"form":form})

@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request, "Article succesfully deleted")
    return redirect("article:dashboard")


@login_required(login_url="user:login")
def addComment(request,id):
    article = get_object_or_404(Article,id=id)

    if request.method == "POST":
        comment_content = request.POST.get("comment")

        newComment = Comment(comment_author=request.user,comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:showdetail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    form = RegisterForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        newUser = User(username=username)
        newUser.set_password(password)
        newUser.save()
        login(request, newUser)
        messages.info(request,"Signed in succesfully")
        return redirect("index")
    context = {
        "form": form
    }
    return render(request, "register.html", context)

    """if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            newUser = User(username= username)
            newUser.set_password(password)
            newUser.save()
            login(request,newUser)
            return redirect("index")
        context = {
            "form": form
        }
        return render(request, "register.html", context)
    else:
        form = RegisterForm()
        context = {
            "form": form
        }
        return render(request,"register.html",context)
"""



def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user=authenticate(username=username, password=password)

        if user is None:
            messages.info(request,"User name or password is not correct")
            return render(request,"login.html",context)
        messages.success(request,"Logged in successfully")
        login(request,user)
        return redirect("index")
    return render(request, "login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"Logged out successfully")
    return redirect("index")

templates/about.html
<!DOCTYPE html>
{% extends "layout.html" %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About Page</h1>
<p>My name is Mustafa Eren Çelebi. This website is my internship project.</p>
</body>
</html>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
        <h3>Articles</h3>
        <hr>

    <form>
    {% csrf_token %}
    <input type="text" name="keyword" class="input-sm">
    <button type="submit" class="btn btn-danger">Search</button>
    </form>
    {% if articles %}
        {% for article in articles %}
            <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->

            <a href="{% url 'article:showdetail' article.id %}"> <h3 class="mt-4">{{article.title}}</h3></a>

      <!-- Author -->
      <p class="lead">

        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:showdetail' article.id  %}"> <img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}


      <hr>

      <!-- Post Content -->
      <!--<p class="lead">
          {{article.content}}
      </p>

      <hr>
        </div>
 </div>-->
    {% endfor %}

    {% else %}
     <div class = "alert alert-danger">No articles</div>
    {% endif %}


{% endblock body %}

templates/createarticle.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}



<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Article</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <br>
            <button type="submit" class="btn btn-danger">Create</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
    <h3>Dashboard</h3>
    <hr>
    <p>
        Welcome <small>{{ request.user.username }}</small>
    </p>
    <hr>
    <a class = "btn btn-danger" href="{% url 'article:createarticle' %}">Create Article</a>
    <hr>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
        <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for article in articles %}
        <tr>
      <th scope="row">{{ article.id }}</th>
      <td><a href = "{% url 'article:showdetail' article.id  %}">{{ article.title }}</a></td>
      <td>{{ article.author }}</td>
      <td>{{ article.created_date }}</td>
        <td><a href = "{% url 'article:update' article.id %}" class = "btn btn-danger">Update</a></td>
        <td><a href = "{% url 'article:delete' article.id  %}" class = "btn btn-danger">Delete</a></td>
    </tr>
  {% endfor %}
  
    <!---<tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr> -->
  </tbody>
</table>
{% endblock body %}

templates/delete.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}



<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Delete Article</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <br>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">

        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}


      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>
        <h4>Comments</h4>
    <hr>
    {% if comments %}
        {% for comment in comments %}
        <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{ comment.comment_date }}<br>
          {{ comment.comment_content }}
        </div>
      </div>
        {% endfor %}


    {% else %}
        <div class="alert alert-danger">No comments</div>
    {% endif %}

         <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
          <form method= "post" action="{% url 'article:comment' article.id %}">
            {% csrf_token %}
            <div class="form-group">
              <textarea name="comment" class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
        </div>
 </div>


{% endblock body %}

templates/includes/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index'  %}">Blog APP</a>
        <a class="navbar-brand" href="{% url 'about'  %}">About</a>
        <a class="navbar-brand" href="{% url 'article:article'  %}">Articles</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'article:dashboard'  %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout'  %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:register'  %}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login'  %}">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Bootstrap JS and Popper.js (required for Bootstrap JavaScript components) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/index.html
{% extends "layout.html" %}

{% block body%}
<div class="jumbotron text-center">
    <h3>Welcome to the Blog</h3>
    <p>In this blog you can share your articles</p>

</div>


{% endblock body%}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <title>Blog</title>
</head>
<body>
        {% include "includes/navbar.html" %}
            {% if messages %}

                    {% for message in messages %}
                        {% if message.tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                        {% else %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                        {% endif %}
                    {% endfor %}

            {% endif %}

        <div style="margin-top : 100px; margin-bottom: 50px; " class="container">
            {% block body %}

            {% endblock body %}
        </div>

        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        <script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>
        <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>


    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}



<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <br>
             <button type="submit" class="btn btn-danger">Log in</button>
        </form>


    </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

<h3>Sign Up</h3>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <br>
    <button type="submit" class = "btn btn-danger">Sign Up</button>
</form>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}



<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Article</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <br>
            <button type="submit" class="btn btn-danger">Update</button>
        </form>
    </div>
</div>

{% endblock body %}